### ISSUE TITLE
Issue on pin 13 triggering keypresses constantly when using teensy 3.1 (and inconsistent pinout for the restore button)

### ISSUE THREAD

**Issue by theshinyknight** [dabonetn/C64USBKey#6]
Just an update about the issue I am having.

Basically following the exact pinout of the sketch; there is an issue with the teensy 3.1. If I use pin13, it just cause the output to constantly return keypress. That is the only pin doing that. To fix the issue I removed pin 13 and used pin 21; that did work just fine, so the row 0 became pin 21 instead of 13, and all the characters are executed correctly.

Although I was not able to solve the issue with the restore button, which does not work. In the sketch there are 2 pin selected (pin 1 and 2), that are covering for the extra row of keys (which I assume are the joystick controls; because from the schematics, the only button on the extra row and column is the restore button, using pin 1 and 3 on the main C64 keyboard connector). Those pins are not connected as pin 1 and 3, but as pin 1 and pin 8, which means that you have to connect 2 different pins from the keyboard connector, to the actual pins of the micro-controller. This has the adverse effect of returning the brace when you press the restore button. Not sure if the diagram in your sketch is wrong or if the pinout is incorrect. There is also another inconsistency with "not needed pins", which mention pin 1 and 2, which are not in the list of the pins you use on the top of the sketch.

**Comment by dabonetn** [comment]
Ok, it's been awhile since I worked on this at all.
First double check the settings for the teensy.
Here are the settings.

Teensy LC programming mode should be the following.
USB Mode: Keyboard
CPU Speed: 24Mhz
Optimize: Smallest Code
Keyboard Layout: US English

It wasn't stable at higher clocks.

For the restore key, I listed the teensy pin wrong, A8 is pin 11 instead of 8.
So, it's doubled up, with pin 1 providing the other side of the signal.

Pin 1 also provides for joystick 1.
Pin 2 is only used for joystick 2.

If you have a Teensy 2.0 I recommend looking at this guys project also.

https://www.keymmodore.com/keymmodore-64/

**Comment by theshinyknight** [comment]
Thanks, worked around the other issues except pin 13, which continue to trigger signals constantly and it is not usable.

So if I want to use the last row and column, I must double the pin 11 with pin 1? Just curious why don't you use another one of the free pins on the Teensy. Thanks

**Comment by dabonetn** [comment]
This originally started on the arduino pro micro, teensy was added at the very end, I have a teensy 2.0 in my pi 64 now.
Why I doubled up on pins, the 64 has a 8x8 matrix, This project was started by someone else (Pyofer) and his had no support for the restore key, because it lives outside of the keyboard matrix, and hooks the NMI to gnd. So instead of adding 2 wires, I just added one more column, and reused a row pin. This also made the scan quicker. The second joystick port added another column.

This is pretty much a dead project. The joystick ports had ghosting issues with some joysticks, but not others. But the keyboard portion works well.
